version: '3.9'
services:
    wordpress:
        image: wordpress:php8.1-apache
        container_name: wordpress
        ports:
            - '8080:80'
        environment:
            - WORDPRESS_DB_HOST="mysql"
            - WORDPRESS_DB_USER="exampleuser"
            - WORDPRESS_DB_PASSWORD="examplepass"
            - WORDPRESS_DB_NAME="exampledb"
        networks:
            - wordpress-net
        volumes:
            - wordpress:/var/www/html

    mysql:
      image: mysql:5.7
      environment:
        - MYSQL_DATABASE="exampledb"
        - MYSQL_USER="exampleuser"
        - MYSQL_PASSWORD="examplepass"
        - MYSQL_RANDOM_ROOT_PASSWORD='1'
      volumes:
        - db:/var/lib/mysql
      networks:
        - wordpress-net
volumes:
  wordpress:
  db:


networks:
    wordpress-net: